export const INQUIRY_REQUEST = "INQUIRY_REQUEST"
export const INQUIRY_SUCCESS = "INQUIRY_SUCCESS"
export const INQUIRY_FAIL = "INQUIRY_FAIL"
export const INQUIRY_RESET = "INQUIRY_RESET"

export const LIST_INQUIRY_REQUEST = "LIST_INQUIRY_REQUEST"
export const LIST_INQUIRY_SUCCESS = "LIST_INQUIRY_SUCCESS"
export const LIST_INQUIRY_FAIL = "LIST_INQUIRY_FAIL"

export const INQUIRY_DETAILS_REQUEST = "INQUIRY_DETAILS_REQUEST"
export const INQUIRY_DETAILS_SUCCESS = "INQUIRY_DETAILS_SUCCESS"
export const INQUIRY_DETAILS_FAIL = "INQUIRY_DETAILS_FAIL"

export const UPDATE_INQUIRY_REQUEST = "UPDATE_INQUIRY_REQUEST"
export const UPDATE_INQUIRY_SUCCESS = "UPDATE_INQUIRY_SUCCESS"
export const UPDATE_INQUIRY_RESET = "UPDATE_INQUIRY_RESET"
export const UPDATE_INQUIRY_FAIL = "UPDATE_INQUIRY_FAIL"

export const DELETE_INQUIRY_REQUEST = 'DELETE_INQUIRY_REQUEST'
export const DELETE_INQUIRY_SUCCESS = 'DELETE_INQUIRY_SUCCESS'
export const DELETE_INQUIRY_RESET = 'DELETE_INQUIRY_RESET'
export const DELETE_INQUIRY_FAIL = 'DELETE_INQUIRY_FAIL'

export const CLEAR_ERRORS = "CLEAR_ERRORS"